department: "csc"
curTerm: "2268"
prevTerm: "2264"
seasonTerm: "fall"
testing: false
useApi: true
# ------- Optional -------
# this setting changes how we model the PrimeTime constraint
aggressiveChoice: "AGGRESSIVE_PENALTY"
compressStart: "7:00AM"
compressEnd: "6:00PM"
prescheduledFileName: "PrescheduledTimes_ExampleFile.example.json"