networks:
  scheduling:
    name: scheduling

services:
  db:
    image: postgres
    restart: always
    container_name: postgres-service
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # if vars are not in .env file use defaults
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-scheduling}
    ports:
      - "5432:5432"
    networks:
      - scheduling
    volumes:
      - pgdata:/var/lib/postgresql/data 
 
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_service
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-example@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "15432:80"
    networks:
      - scheduling
    volumes:
      - pgadmin-data:/var/lib/pgadmin

# volumes for postgres and pgadmin
volumes:
  pgdata:
  pgadmin-data: