# Generated by Django 5.2.6 on 2025-10-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_teacher_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='cpe',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='csc',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='faculty',
            field=models.BooleanField(default='False'),
        ),
    ]
