# Generated by Django 5.2.6 on 2025-10-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_teacher_cpe_teacher_csc_teacher_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='canon',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='non_canon',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
