# Generated by Django 5.2.6 on 2025-10-05 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_teacher_canon_alter_teacher_non_canon'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('bleed_forward', models.CharField(max_length=150)),
                ('mwf_7_am', models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20)),
                ('mwf_8_am', models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20)),
                ('mwf_9_am', models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20)),
                ('mwf_10_am', models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20)),
                ('mwf_11_am', models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20)),
                ('mwf_12_pm', models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20)),
                ('mwf_1_pm', models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20)),
                ('mwf_2_pm', models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20)),
                ('mwf_3_pm', models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20)),
                ('mwf_4_pm', models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20)),
                ('mwf_5_pm', models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20)),
                ('mwf_6_pm', models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20)),
                ('mwf_7_pm', models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20)),
                ('mwf_8_pm', models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20)),
                ('mwf_9_pm', models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20)),
                ('tr_7_am', models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20)),
                ('tr_8_am', models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20)),
                ('tr_9_am', models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20)),
                ('tr_10_am', models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20)),
                ('tr_11_am', models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20)),
                ('tr_12_pm', models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20)),
                ('tr_1_pm', models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20)),
                ('tr_2_pm', models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20)),
                ('tr_3_pm', models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20)),
                ('tr_4_pm', models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20)),
                ('tr_5_pm', models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20)),
                ('tr_6_pm', models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20)),
                ('tr_7_pm', models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20)),
                ('tr_8_pm', models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20)),
                ('tr_9_pm', models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20)),
                ('mwf_1', models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], max_length=20)),
                ('tr_1', models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], max_length=20)),
                ('mwf_2', models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], max_length=20)),
                ('mwf_tr', models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], max_length=20)),
                ('tr_2', models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], max_length=20)),
                ('mwf_3', models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], max_length=20)),
                ('mwf_2_tr_1', models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], max_length=20)),
                ('mwf_1_tr_2', models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], max_length=20)),
                ('tr_3', models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], max_length=20)),
                ('mwrf', models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], max_length=20)),
                ('mtwr', models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], max_length=20)),
                ('mw', models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], max_length=20)),
                ('tr', models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], max_length=20)),
                ('back_to_back', models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], max_length=20)),
                ('gap', models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], max_length=20)),
                ('constraint', models.TextField()),
                ('require', models.TextField()),
                ('pref', models.TextField()),
                ('comment', models.TextField()),
                ('stars', models.TextField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher')),
            ],
        ),
    ]
