# Generated by Django 5.2.6 on 2025-10-06 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_teacher_email_survey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='teacher',
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_canon', models.BooleanField()),
                ('name', models.CharField(max_length=100, unique=True)),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher')),
            ],
        ),
    ]
