# Generated by Django 5.2.6 on 2025-10-06 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_survey_teacher_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
