# Generated by Django 5.2.6 on 2025-12-19 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_teacher_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='teacher',
            new_name='teacher_id',
        ),
    ]
