# Generated by Django 5.2.6 on 2025-12-19 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_teacher_history_teacher_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
