# Generated by Django 5.2.6 on 2025-12-30 08:52

import api.model_validators.survey_validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_teacher_id_history_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='bleed_forward',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='complete',
        ),
        migrations.AddField(
            model_name='survey',
            name='cur_term',
            field=models.CharField(default='badV', validators=[api.model_validators.survey_validators.term_checker]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='prev_term',
            field=models.CharField(default='badV', validators=[api.model_validators.survey_validators.term_checker]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='teacher',
            field=models.ForeignKey(default=56, on_delete=django.db.models.deletion.CASCADE, to='api.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='use_old',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survey',
            name='back_to_back',
            field=models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], max_length=20, validators=[api.model_validators.survey_validators.pref_validator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='gap',
            field=models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], max_length=20, validators=[api.model_validators.survey_validators.pref_validator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='mtwr',
            field=models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], max_length=20, validators=[api.model_validators.survey_validators.pref_validator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='mw',
            field=models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], max_length=20, validators=[api.model_validators.survey_validators.pref_validator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='mwf_1',
            field=models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], max_length=20, validators=[api.model_validators.survey_validators.pref_validator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='mwf_10_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='mwf_11_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='mwf_12_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='mwf_1_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='mwf_1_tr_2',
            field=models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], max_length=20, validators=[api.model_validators.survey_validators.pref_validator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='mwf_2',
            field=models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], max_length=20, validators=[api.model_validators.survey_validators.pref_validator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='mwf_2_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='mwf_2_tr_1',
            field=models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], max_length=20, validators=[api.model_validators.survey_validators.pref_validator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='mwf_3',
            field=models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], max_length=20, validators=[api.model_validators.survey_validators.pref_validator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='mwf_3_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='mwf_4_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='mwf_5_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='mwf_6_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='mwf_7_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='mwf_7_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='mwf_8_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='mwf_8_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='mwf_9_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='mwf_9_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='mwf_tr',
            field=models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], max_length=20, validators=[api.model_validators.survey_validators.pref_validator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='mwrf',
            field=models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], max_length=20, validators=[api.model_validators.survey_validators.pref_validator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='tr',
            field=models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], max_length=20, validators=[api.model_validators.survey_validators.pref_validator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='tr_1',
            field=models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], max_length=20, validators=[api.model_validators.survey_validators.pref_validator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='tr_10_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='tr_11_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='tr_12_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='tr_1_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='tr_2',
            field=models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], max_length=20, validators=[api.model_validators.survey_validators.pref_validator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='tr_2_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='tr_3',
            field=models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], max_length=20, validators=[api.model_validators.survey_validators.pref_validator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='tr_3_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='tr_4_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='tr_5_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='tr_6_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='tr_7_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='tr_7_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='tr_8_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='tr_8_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='tr_9_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='tr_9_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddConstraint(
            model_name='survey',
            constraint=models.UniqueConstraint(fields=('teacher', 'cur_term'), name='teacher_term_unique'),
        ),
    ]
