# Generated by Django 5.2.6 on 2026-01-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_survey_bleed_forward_remove_survey_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='constraint',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='pref',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='require',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='stars',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='use_old',
            field=models.BooleanField(blank=True),
        ),
    ]
