# Generated by Django 5.2.6 on 2026-02-13 02:13

import api.model_validators.survey_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_survey_comment_alter_survey_constraint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='mwf_10_am',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='mwf_11_am',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='mwf_12_pm',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='mwf_1_pm',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='mwf_2_pm',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='mwf_3_pm',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='mwf_4_pm',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='mwf_5_pm',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='mwf_6_pm',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='mwf_7_am',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='mwf_7_pm',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='mwf_8_am',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='mwf_8_pm',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='mwf_9_am',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='mwf_9_pm',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='tr_10_am',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='tr_11_am',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='tr_12_pm',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='tr_1_pm',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='tr_2_pm',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='tr_3_pm',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='tr_4_pm',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='tr_5_pm',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='tr_6_pm',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='tr_7_am',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='tr_7_pm',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='tr_8_am',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='tr_8_pm',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='tr_9_am',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='tr_9_pm',
        ),
        migrations.AddField(
            model_name='survey',
            name='f_10_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='f_11_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='f_12_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='f_1_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='f_2_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='f_3_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='f_4_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='f_5_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='f_6_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='f_7_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='f_7_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='f_8_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='f_8_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='f_9_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='f_9_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='m_10_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='m_11_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='m_12_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='m_1_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='m_2_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='m_3_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='m_4_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='m_5_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='m_6_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='m_7_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='m_7_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='m_8_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='m_8_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='m_9_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='m_9_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='r_10_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='r_11_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='r_12_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='r_1_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='r_2_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='r_3_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='r_4_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='r_5_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='r_6_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='r_7_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='r_7_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='r_8_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='r_8_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='r_9_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='r_9_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='t_10_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='t_11_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='t_12_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='t_1_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='t_2_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='t_3_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='t_4_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='t_5_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='t_6_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='t_7_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='t_7_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='t_8_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='t_8_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='t_9_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='t_9_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='w_10_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='w_11_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='w_12_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='w_1_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='w_2_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='w_3_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='w_4_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='w_5_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='w_6_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='w_7_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='w_7_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='w_8_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='w_8_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='w_9_am',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='w_9_pm',
            field=models.CharField(choices=[('Preferred', 'Preferred'), ('Conflict', 'Conflict'), ('Acceptable', 'Acceptable'), ('', 'Conflict')], default='Conflict', max_length=20, validators=[api.model_validators.survey_validators.avail_vailidator]),
        ),
    ]
