# Generated by Django 5.2.6 on 2026-02-13 04:14

import api.model_validators.survey_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_survey_mwf_10_am_remove_survey_mwf_11_am_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='mtwr',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='mw',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='mwf_1',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='mwf_1_tr_2',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='mwf_2',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='mwf_2_tr_1',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='mwf_3',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='mwf_tr',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='mwrf',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='tr',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='tr_1',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='tr_2',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='tr_3',
        ),
        migrations.AddField(
            model_name='survey',
            name='lecAct_1hrLec',
            field=models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], default='Disagree', max_length=20, validators=[api.model_validators.survey_validators.pref_validator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='lecAct_2hrAct',
            field=models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], default='Disagree', max_length=20, validators=[api.model_validators.survey_validators.pref_validator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='lecAct_noPref',
            field=models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], default='Disagree', max_length=20, validators=[api.model_validators.survey_validators.pref_validator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='lecAct_notSure',
            field=models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], default='Disagree', max_length=20, validators=[api.model_validators.survey_validators.pref_validator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='pref_5days',
            field=models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], default='Disagree', max_length=20, validators=[api.model_validators.survey_validators.pref_validator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='pref_TPD',
            field=models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], default='Disagree', max_length=20, validators=[api.model_validators.survey_validators.pref_validator]),
        ),
        migrations.AddField(
            model_name='survey',
            name='pref_minDays',
            field=models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], default='Disagree', max_length=20, validators=[api.model_validators.survey_validators.pref_validator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='back_to_back',
            field=models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], default='Disagree', max_length=20, validators=[api.model_validators.survey_validators.pref_validator]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='gap',
            field=models.CharField(choices=[('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('', 'Disagree')], default='Disagree', max_length=20, validators=[api.model_validators.survey_validators.pref_validator]),
        ),
    ]
